services:
  - type: web
    name: cantina-pos-backend
    env: node
    buildCommand: cd pos-backend && yarn install
    startCommand: cd pos-backend && yarn start
    envVars:
      - key: PORT
        value: "5000"
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
