services:
  - type: web
    name: cantina-pos-backend
    env: node
    rootDir: ./pos-backend
    buildCommand: yarn install
    startCommand: yarn start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
